version: '3.5'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=solarheaven

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    image: backend-app
    command: pnpm --filter server run dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=3000
      - JWT_SECRET=jwt_secret
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=solarheaven
      - GOOGLE_CLIENT_ID=90852100444-ra5b8vjms9l7h2llautgp3n6bglc6taj.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    command: pnpm --filter client run dev
    ports:
      - "3000:3000"
    depends_on:
      - db

  pgadmin:
    container_name: solarheaven-pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    depends_on:
      - db
